### ISSUE TITLE
could not import PACKAGE (no metadata for PACKAGE) if wire in _test package

### ISSUE THREAD

**Issue by elegos** [google/wire#100] opened 2018-12-26 00:20 UTC
### Describe the bug

I'm trying to use wire in a go 1.11.1 module, but wire is not able to get the metadata for the imported packages if the wire.go file has a `_test` suffix. Am I missing how to create dependency containers for testing packages?

### To Reproduce

Create a simple foo/bar dependency in package `service`, then in the same folder create a `wire.go` file with `package service_test` and build with the two deps, like this:

Foo.go:
```go
package service

import "fmt"

type Foo string

func NewFoo() Foo {
	return Foo(fmt.Sprintf("foo! %s", "foo foo"))
}
```

Bar.go:
```go
package service

type Bar struct {
	MyFoo Foo
}

func NewBar(foo Foo) *Bar {
	return &Bar{
		MyFoo: foo,
	}
}
```

wire.go:
```go
//+build wireinject

package service_test

import (
	"wire-error-poc/service"

	"github.com/google/wire"
)

func GetBar() *Bar {
	wire.Build(service.NewFoo, serviceNewBar)

	return &Bar{}
}
```

## Expected behavior

I expect to see a `wire_gen.go` file containing the `GetBar` function in the `service_test` package (for testing purposes)

### Version

0.2.0

### Additional context

Files tree:
```
<root>
| - services
| - - Foo.go
| - - Bar.go
| - - wire.go
```

wire command output:

```
$ cd <root>/services
$ wire
-: found packages service (bar.go) and service_test (wire.go) in /home/elegos/Development/proof_of_concept/wire-error-poc/service
/home/elegos/Development/proof_of_concept/wire-error-poc/service/wire.go:3:1: package service_test; expected service
/home/elegos/Development/proof_of_concept/wire-error-poc/service/foo.go:3:8: could not import fmt (no metadata for fmt)
wire: generate failed
```

#### System details

```
go version go1.11.1 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/elegos/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/elegos/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go-1.11.1"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go-1.11.1/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/elegos/Development/proof_of_concept/wire-error-poc/go.mod"
uname -sr: Linux 4.19.10-300.fc29.x86_64
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 29 (Twenty Nine)
Release:	29
Codename:	TwentyNine
/lib64/libc.so.6: GNU C Library (GNU libc) stable release version 2.28.
gdb --version: GNU gdb (GDB) Fedora 8.2-5.fc29
```

**Comment by vangent** [comment] 2019-01-02 16:42
Hi @elegos , thanks for filing the issue. I believe it is a duplicate of #48, can you confirm?

**Comment by elegos** [comment] 2019-01-03 14:00
Yep @vangent, I think I must have missed it :)

**Comment by vangent** [comment] 2019-01-03 16:19
OK, marking closed then. I'll add you to the other issue.

Duplicate of #48.

**Closed by vangent** 2019-01-03 16:19 UTC
Labels: duplicate
